### ISSUE TITLE
Javascript - Getting API keys 

### ISSUE THREAD

**Issue by frootloops64** [wesleyroach/FirstProject#11]
## User Story
As a developer, I want to access the JSON responses, so that I can have the information I need populate the web page with real time data. 

## Tasks
- [ ] Google/Geo-tagging API
- [ ] EventBrite API
- [ ] MeetUp API

**Comment by Stephen-dsouza** [comment]
'https://www.eventbriteapi.com/v3/categories/?token=C3OEMSDYCFYJTK2H3KS2'
